task 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -4,6 +4,14 @@
 if [ $# -lt 4 ] 
 then 
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2"
+
+if [ $? -eq 0 ]
+then
+    echo "File transfer was successful"
 else
-    scp "$1" "$3@$2:$4"
+    echo "File transfer failed"
 fi
